services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    networks:
      - net
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - net

networks:
  net:
    driver: bridge